openapi: "3.0.0"
info:
  version: 1.0.0
  title: custom-echo-ctx
  description: custom-echo-ctx
paths:
  /oapi/signup:
    post:
      description: userã®æ–°è¦ç™»éŒ²
      operationId: signup
#      security:
#        #ã“ã‚Œã‚’ã¤ã‘ã‚‹ã¨swagger uiã®éµãƒãƒ¼ã‚¯ãŒåå¿œã—ãªããªã‚‹
#        #ãŸã warningãŒã§ã‚‹ã®ã§å¥½ã¾ã—ããªã„
#        -
      requestBody:
        description: ç™»éŒ²ã™ã‚‹ãƒ¦ãƒ¼ã‚¶ãƒ¼ã®æƒ…å ±
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"
      responses:
        "200":
          description: signup response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /oapi/login:
    post:
      description: userã®ãƒ­ã‚°ã‚¤ãƒ³
      operationId: login
      requestBody:
        description: ãƒ­ã‚°ã‚¤ãƒ³ã™ã‚‹ãƒ¦ãƒ¼ã‚¶ãƒ¼ã®æƒ…å ±
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"
      responses:
        "200":
          description: login response
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
                example:
                  token: example-token
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  #ã“ã‚Œã‚’ã¤ã‘ã‚‹ã¨swagger uiã®ä¸Šéƒ¨ã«AuthorizeğŸ”“ãŒã¤ã„ã¦tokenã‚’ã„ã˜ã‚Œã‚‹
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
  schemas:
    user:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          minLength: 1
          maxLength: 20
        password:
          type: string
          minLength: 8
          maxLength: 20
      required:
        - name
        - password
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
security:
  #ã“ã‚Œã‚’ã¤ã‘ã‚‹ã¨å„Pathã«AuthorizeğŸ”“ãŒã¤ã„ã¦tokenã‚’ã„ã˜ã‚Œã‚‹
  - bearerAuth: []         # use the same name as above